### ISSUE TITLE
已注册界面未出现提示信息

### ISSUE THREAD

**Issue by Ais-Danny** [weiran1999/seckill-front#2]
![image](https://github.com/weiraneve/seckill-front/assets/91066083/2c3f1a92-fffa-44ee-8336-2d00f30e93e5)

**Comment by weiraneve** [comment]
这一个我看了，是antd message渲染不知道为啥跑到左上角，且在所有渲染body的后面导致的.....

**Comment by weiraneve** [comment]
![antd_message_error](https://github.com/weiraneve/seckill-front/assets/60456779/31291d8f-e829-4fc7-8bd2-a181e2af3335)

这里的问题暂且从代码没看出来为何会出现，可能是因为vite 导致的....

**Comment by weiraneve** [comment]
回滚vite的feature，已解决该问题
